### PR TITLE
Add mainnet genesis file, update readme

### PR DESCRIPTION
**Pull request by JakeHartnell**

### CODE REVIEW

**Review by zlounes — APPROVED** [review]
Let's go!!!!!  🥳 🤩

**Review by nullmames — APPROVED** [review]
looks good

**Comment by JakeHartnell** [comment]
Added some seed nodes.

**Comment by dimiandre** [comment]
lgtm!

**Review by dimiandre — APPROVED** [review]

**Review by blockcreators — APPROVED** [review]
looks good

**Comment by orkunkl** [comment]
🚀

**Comment by the-frey** [comment]
🥇 🚀 🚀 🚀

**Pull request merged**
