### PR TITLE
Lupercalia draft instrux

### PR DESCRIPTION
**Pull request by the-frey**
Instructions for the Lupercalia upgrade.

### CODE REVIEW

**Review by JakeHartnell — APPROVED** [review]
LGTM

**Comment by giansalex** [comment]
reference about wasm-cache-v1  should be added?   to clear disk space
https://discord.com/channels/816256689078403103/898335064465743963/941745855495561268

**Comment by the-frey** [comment]
@giansalex good point. Have added a note about wasm cache

**Comment by giansalex** [comment]
i saw a new version `v3-wasmer1`,  but docs are ok, mainnet only has v1 dir.

On testnet we can remove `.juno/data/wasm/cache/modules/v2`

**Pull request merged**
