### PR TITLE
add persistent_peers.txt

### PR DESCRIPTION
**Pull request by nullmames**
add persistent_peers.txt
add Mitera peer

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Lot's of unrelated commits for one file change. Can you squash them?

Squashing info:
- https://www.git-tower.com/learn/git/faq/git-squash/
- https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

Or submit a new PR.

**Review by JakeHartnell — CHANGES_REQUESTED** [review]
Squash commits please.

Also, this node is one that has submitted their gentx and will be online at network start?

**Comment by nullmames** [comment]
can this be squashed on merge?

**Comment by nullmames** [comment]
validator is in gentx FreshJUNO

@gaia

**Comment by nullmames** [comment]
Closing PR to squash

**Pull request closed without merging**
